

@startuml
'This is a comment
'https://plantuml.com/class-diagram

title Class Diagram Sample

'Interfaces & abstract classes
abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

'Enums
enum TimeUnit {
  DAYS
  HOURS
  MINUTES
}

'Classes
class ArrayList {
  Object[] elementData
  size()
}

'Relationships
List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

package "Classic Collections" #DDDDDD {
  Object <|-- ArrayList
}

'Decorators/Anotations
annotation SuppressWarnings

annotation Annotation {
  annotation with members
  String foo()
  String bar()
}

@enduml

@startuml

title Remotecontrol Keyboard Builder Model
'The aim of this model is make it possible build a serializable keyboard layout
'The keyboad layout is a tree of keys and layout elements
'Some key types are:
' - KeyboardKey: a key that sends a keyboard key key code
' - MouseKey: a key that sends a mouse key key code
' - MouseMoveKey: a key that sends a mouse move key code and move delta
' - KeySequence: a key composed of other keys
'Some layout elements are:
' - HorizontalSpacer
' - VerticalSpacer
' -
'Serializable hierarchical

package rendering {
	abstract class Geometry {}
	'element is a displayable control that can be added to a container
  abstract class Element {
  	+geometry Geometry
  	+label string

  	+build()
  }
	abstract class Layout {
		geometry Geometry
		children: Element[]
	}

	class FlexibleGeometry {
		maxWidth: float?
    maxHeight: float?
    expand: bool?
    padding: Padding?
	}

	class FlexLayout {
		+geometry: FlexibleGeometry
		+description: string
    +direction: "row" | "column"
    +columnGap: float
    +rowGap: float
	}

	class HorizontalSpacer {}
	class VerticalSpacer {}

	'Relationships
	Element <|-- Layout
	Layout <|-- FlexLayout
	Layout *- Geometry : "1..*"
	Geometry <|-- FlexibleGeometry
	FlexLayout *- FlexibleGeometry : "1..*"
	Element <|-- HorizontalSpacer
	Element <|-- VerticalSpacer
}

package actions {
	'action is the base class for all actions
	abstract class Command {}

	abstract class Action {
		+getCommands() : Command[]
	}
	note right of Action::getCommands
		Each action can have multiple commands
		associated with it.
	end note

	class SequenceAction {
		actions Action[]
	}

	enum KeyState {
		Up
		Down
	}

	abstract class KeyAction {
		state KeyState
	}

	class KeyboardKeyAction {
		keyCode KbdKeyCode
	}

	class MouseButtonAction {
		keyCode MbKeyCode
	}

	class TypeTextAction {
  	text string
  }

  class ShowMenuAction {
    hideOnRelease: bool
    pressOnRelease: bool
    actions: Action[]
  }

  Action <|-- TypeTextAction
  Action <|-- SequenceAction
  Action <|-- ShowMenuAction
  Command -* Action
  Action --* SequenceAction
  Action <|-- KeyAction
  KeyAction <|-- KeyboardKeyAction
  KeyAction <|-- MouseButtonAction
	KeyState *- KeyAction
}

package interactive {
	class Button {
		+geometry: FlexibleGeometry
		+label: string
		+keyRepeat: float
	  +keyRepeatDelay: float
	  +toggle: bool
	  -action Action
		+holdTimeThreshold: float
	  -holdAction Action?
	  +doubleTapThershold: float
	  -doubleTapAction Action?

		+build()
	}
	class Touchpad {
		+sensitivity int?
		+scrollbar bool
		+mouseButtons bool
		+tapToClick bool
		+doubleTapAndHold bool

		+build()
	}


	'Relationships
	Action --* Button::action
	Element <|-- Button
	Element <|-- Touchpad
}

@enduml
